In [3]:
import numpy as np
import sympy
from sympy import Matrix
from scipy.stats import sem

import scipy
import scipy.linalg as sla
from scipy.linalg import *

In [27]:
#converting from TBB to TCC cell

mat = np.array([[-1,-3,-2],[0,1,-2],[2,0,0]])
mat2 = np.linalg.inv(mat)
mat1 = np.array([[0,0,-2],[-2,1,0],[-1,1,-1]])

#multiply inverse with basis2 * 
p = mat2@mat1@mat
#m =np.linalg.solve(mat,[[0],[2],[-4]])
#mat = mat@[[2],[0],[4]]
p

array([[-0.5   ,  2.    ,  0.    ],
       [ 1.625 ,  1.25  ,  0.5   ],
       [-0.1875, -2.875 , -0.75  ]])

In [149]:
#Rref cell

mat = Matrix([[0,3,-1,-1,0],[0,0,4,2,0],[0,0,0,1,1]])

mat = Matrix([[1,1,2],[1,-1,0]])
mat = mat.rref()
mat

(Matrix([
 [1, 0, 1],
 [0, 1, 1]]), (0, 1))

In [148]:
#Nullspace cell
mat  = Matrix([[0,0,0], [1, -1,1],[1, -1,1]]) 
mat = mat.T
mat = mat.nullspace()
mat

[Matrix([
 [1],
 [0],
 [0]]), Matrix([
 [ 0],
 [-1],
 [ 1]])]

In [8]:
#determinant
mat = Matrix( [[-5,-8,-1],[-8,-8,0],[0,-5,-1]])
mat = mat.det()
mat


-16

In [54]:
#Orthogonal basis of a matrix (dont confuse w orthogonal complement)
mat = [[0,-1,0],[-1,0,1],[0,-1,-1]]
mat = sla.orth(mat)
mat


array([[0., 1.],
       [1., 0.]])

In [48]:
#Solving LU equations

f = [[1],[2],[3]]
K = Matrix([[2,3,3],[0,1,2],[0,0,6]])

P,L,U = sla.lu(K)
c = sla.solve_triangular(L,P.T@f, lower = True)
x = sla.solve_triangular(U,c)
x

array([[-1.75],
       [ 1.  ],
       [ 0.5 ]])

In [147]:
#inverse cell and tcc
A = np.array([[-1,-1],[-1,1]])
k = np.linalg.inv(A)
#tcc = [[-2,-1,-3], [-1,0,1], [0,1,1]]
#k = k@tcc@A
k


array([[-0.5, -0.5],
       [-0.5,  0.5]])

In [101]:
mat =Matrix([[-1,-3,-3,0],[0,-2,-4, 0],[-2,0,6,0], [0,-2,-4,0]])
mat = mat.rref()
mat 

(Matrix([
 [1, 0, -3, 0],
 [0, 1,  2, 0],
 [0, 0,  0, 0],
 [0, 0,  0, 0]]), (0, 1))

In [1]:
#only for sqyare
mat = np.array([[-1,-3,-3],[0,-2,-4],[-2,0,6],[0,-2,-4]])
#m =np.linalg.solve(mat,[[0],[0],[0],[0]])
a = np.array([[0,0],[0,0]])
mat = sla.solve(mat,a)
print(mat)

NameError: name 'np' is not defined

In [ ]:
#graph function for finding number of connections to people
import numpy as np
import numpy.linalg as la

M = friends + np.eye(np.shape(friends)[0])
Z = la.matrix_power(M, 1)
Z = (Z>0).astype(int)
unique_groups = np.unique(Z, axis = 0)
num_friend_groups = np.shape(unique_groups)[0]



k = 100
num_meme_spread = 0
for i in range (k):
    num_meme_spread += Z[i][70]
    



def meme_spread(friends, origin):
  # friends: 2d numpy array with the friend social network
  # origin: integer with the person starting sending the meme
  # write your code here
    
    k = np.shape(friends)[0]
    M = friends + np.eye(k)
    
    Z = la.matrix_power(M, k-1)
    
    Z = (Z>0).astype(int)
    
    integer_number_people_that_see_the_meme = 0
    for i in range (k):
        integer_number_people_that_see_the_meme += Z[i][origin]
    
    
    return integer_number_people_that_see_the_meme


  
  
  